ci:
  autoupdate_commit_msg: 'Bump `pre-commit` Dependency Versions'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  # Does not have support for PEP 695 generics yet
  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: v1.10.1
  #    hooks:
  #      - id: mypy
  #        name: mypy
  #        files: ^(?!(tests)).*\.py$
  #        args:
  #          - --install-types
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.371
    hooks:
      - id: pyright
        name: pyright
        files: ^(?!(tests)).*\.py$
        additional_dependencies:
          - sphinx~=7.3
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus
