name: chango
description:
branding:
  icon: book-open
  color: gray-dark
inputs:
  python-version:
    description: Python version to use. See actions/setup-python for more information. Default is 3.x
    required: false
    default: 3.x

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install chango
      id: install-chango
      shell: bash
      run: |
        python -W ignore -m pip install .

    - name: Dump GitHub Context
      id: dump-github-context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Compare Completeness
      id: compare-completeness
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
          from chango._cli.config_module import get_chango_instance
          chango_instance = get_chango_instance()
          slug = f"{${{ github.event.pull_request.number }}:04}"
          
          change_note = chango_instance.build_template_change_note(slug=slug)
          chango_instance.write_change_note(change_note, version=None)

    - name: Commit and Push
      id: commit-and-push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Add chango fragment for PR ${{ github.event.pull_request.number }}"
