name: chango
description:
branding:
  icon: book-open
  color: gray-dark
inputs:
  python-version:
    description: Python version to use. See actions/setup-python for more information. Default is 3.x
    required: false
    default: 3.x
  commit-and-push:
    description: Whether to commit and push the changes to the PR branch. Default is true.
    required: false
    default: true
  pyproject-toml:
    description: Path to the ``pyproject.toml`` file. Takes the same input as ``chango.config.get_chango_instance``.
    required: false
    # Using python naming here ensures that we can directly use this value below.
    default: None

runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install chango
      id: install-chango
      shell: bash
      run: |
        python -W ignore -m pip install .

    - name: Create chango fragment
      id: create-chango-fragment
      uses: jannekem/run-python-script-action@bbfca66c612a28f3eeca0ae40e1f810265e2ea68 # v1.7
      with:
        script: |
          from chango.config import get_chango_instance
          chango_instance = get_chango_instance(${{ inputs.pyproject-toml }})
          
          null = None
          false = False
          true = True

          change_note = chango_instance.build_github_event_change_note(${{ toJson(github.event) }})
          chango_instance.write_change_note(change_note, version=None)

    - name: Commit and Push
      id: commit-and-push
      if: ${{ inputs.commit-and-push == 'true' }}
      uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
      with:
        commit_message: "Add chango fragment for PR #${{ github.event.pull_request.number }}"
