name: Create Chango Fragment
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  create-chango-fragment:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    name: create-chango-fragment
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Linked Issues & Parent PR
        id: fetch-linked-issues
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const pullRequest = context.payload.pull_request;
            const octokit = context.octokit;
            
            // Fetch the linked issues
            const { data } = await github.graphql(`
              query {
                pullRequest(number: ${pullRequest.number}, repositoryOwner: "${context.repo.owner}", repositoryName: "${context.repo.repo}") {
                  closingIssuesReferences {
                    nodes {
                      issue {
                        number
                        labels(first: 100) {
                          nodes {
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `);
            const closingIssues = data.pullRequest.closingIssuesReferences.nodes.map(node => {
              const issue = node.issue;
                return {
                number: issue.number,
                labels: issue.labels.nodes.map(label => label.name)
              };
            });
            
            // Fetch the parent PR
            const { data } = await github.graphql(`
              query {
                search(type: ISSUE, query: "is:open is:pr base:main head:${context.payload.pull_request.base.ref}", first: 100) {
                  issueCount
                  nodes {
                    ... on PullRequest {
                      number
                      title
                      url
                      state
                    }
                  }
                }
              }
            `);
            const prs = data.search.nodes;
            const parentPR = prs.length > 0 ? prs[0] : null;
            
            // Combine the linked issues and the parent PR to a single JSON object
            const linkedIssuesAndParentPR = {
              linked_issues: closingIssues,
              parent_pull_request: parentPR
            };
            core.setOutput('data', JSON.stringify(linkedIssuesAndParentPR));

      # Create the new fragment
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./
        with:
          data: ${{ steps.fetch-linked-issues.outputs.data }}

