name: Create Chango Fragment
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  create-chango-fragment:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    name: create-chango-fragment
    runs-on: ubuntu-latest
    steps:
      # Create the new fragment
      - uses: actions/checkout@v4
      - uses: ./
        with:
          commit-and-push: false

      # Render the Version History
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Chango
        id: install-chango
        run: |
          python -W ignore -m pip install .
      - name: Render Version History
        id: render-version-history
        run: |
          chango report history -o changes/CHANGES.rst -m rst

      - name: Commit and Push
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add chango fragment for PR #${{ github.event.pull_request.number }}"

