name: Create Chango Fragment
on:
  pull_request

jobs:
  create-chango-fragment:
    name: create-chango-fragment
    runs-on: ubuntu-latest
    steps:
      - name: Dump SHA
        id: dump-sha
        run: echo "${{ github.event.pull_request.head.sha }}"
      - uses: Bibo-Joshi/chango@main
