name: Create Chango Fragment
on:
  pull_request

jobs:
  create-chango-fragment:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    name: create-chango-fragment
    runs-on: ubuntu-latest
    steps:
      - name: Dump SHA
        id: dump-sha
        run: echo "${{ github.event.pull_request.head.sha }}"
      - uses: Bibo-Joshi/chango@gh-actions
