name: Create Chango Fragment
on:
  pull_request

jobs:
  create-chango-fragment:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    name: create-chango-fragment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
