name: Test Documentation Build
on:
  pull_request:
    paths:
      - src/**
      - '**.rst'
      - '.github/workflows/doc_build_test.yml'
  push:
    branches:
      - main

jobs:
  test-sphinx-build:
    name: test-sphinx-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            pyproject.toml
      - name: Install dependencies
        run: |
          python -W ignore -m pip install --upgrade pip
          python -W ignore -m pip install -r requirements-dev.txt
      - name: Build docs
        run: sphinx-build docs/source docs/build/html -W --keep-going -j auto
