name: Check Type Completeness
on:
  pull_request:
    paths:
      - src/**
      - pyproject.toml
      - .github/workflows/type_completeness_test.yml
  push:
    branches:
      - main

jobs:
  test-type-completeness:
    name:   test-type-completeness
    runs-on: ubuntu-latest
    steps:
      - uses: Bibo-Joshi/pyright-type-completeness@c85a67ff3c66f51dcbb2d06bfcf4fe83a57d69cc # v1.0.1
        with:
          package-name: chango
          python-version: 3.12
